"use client";

import React, { useState } from "react";
import { RegressionTest } from "../types/tracemind";

interface RegressionTestPanelProps {
  regressionTest: RegressionTest | null;
  onGenerate: () => void;
  isLoading?: boolean;
}

export const RegressionTestPanel: React.FC<RegressionTestPanelProps> = ({
  regressionTest,
  onGenerate,
  isLoading = false,
}) => {
  const [copied, setCopied] = useState<boolean>(false);

  const handleCopy = async () => {
    if (!regressionTest) return;
    try {
      await navigator.clipboard.writeText(JSON.stringify(regressionTest, null, 2));
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      setCopied(false);
    }
  };

  return (
    <div className="flex flex-col gap-4 bg-slate-900/60 border border-slate-800 rounded-xl p-5 sm:p-6 shadow-xl backdrop-blur-sm">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 border-b border-slate-800/80 pb-4">
        <div>
          <div className="flex items-center gap-2">
            <h3 className="text-base font-bold font-mono text-slate-100">
              Regression Test Artifact
            </h3>
            <span className="px-2 py-0.5 rounded text-[10px] font-mono font-bold bg-indigo-500/10 text-indigo-400 border border-indigo-500/30 uppercase">
              JSON Spec
            </span>
          </div>
          <p className="text-xs text-slate-400 font-mono mt-0.5">
            Generated JSON test definition to prevent failure reoccurrence in CI/CD pipelines
          </p>
        </div>

        {!regressionTest && (
          <button
            type="button"
            onClick={onGenerate}
            disabled={isLoading}
            className="px-4 py-2 rounded-lg bg-indigo-600 hover:bg-indigo-500 text-white font-mono text-xs font-semibold shadow-lg shadow-indigo-500/10 transition-colors flex items-center gap-2 self-start sm:self-auto disabled:opacity-50"
          >
            {isLoading ? (
              <>
                <span className="w-3.5 h-3.5 border-2 border-white border-t-transparent rounded-full animate-spin"></span>
                Generating Spec...
              </>
            ) : (
              <>
                <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                </svg>
                Generate Regression Test
              </>
            )}
          </button>
        )}

        {regressionTest && (
          <button
            type="button"
            onClick={handleCopy}
            className="px-3 py-1.5 rounded bg-slate-800 hover:bg-slate-700 text-slate-200 font-mono text-xs transition-colors border border-slate-700 flex items-center gap-1.5 self-end sm:self-auto"
          >
            {copied ? (
              <span className="text-emerald-400 font-semibold flex items-center gap-1">
                ✓ Copied JSON Artifact
              </span>
            ) : (
              <span>Copy Test Artifact</span>
            )}
          </button>
        )}
      </div>

      {isLoading && (
        <div className="flex flex-col items-center justify-center p-8 bg-slate-950 rounded-lg border border-slate-800 font-mono text-xs text-slate-400 animate-pulse">
          Synthesizing minimal inputs and assertion patterns...
        </div>
      )}

      {regressionTest && (
        <div className="flex flex-col gap-3">
          <div className="relative rounded-lg border border-slate-800 bg-slate-950 overflow-hidden shadow-inner">
            <div className="max-h-[400px] overflow-auto p-4 font-mono text-xs text-slate-300 leading-relaxed scrollbar-thin scrollbar-thumb-slate-800">
              <pre className="whitespace-pre-wrap break-words">
                {JSON.stringify(regressionTest, null, 2)}
              </pre>
            </div>
          </div>

          <div className="flex items-center gap-2 p-3 rounded-lg bg-indigo-950/20 border border-indigo-900/40 text-xs font-mono text-indigo-300">
            <svg className="w-4 h-4 text-indigo-400 shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
            </svg>
            <span>
              Note: This artifact is generated by ICHNOUS to specify minimal inputs and mock outputs. Import it into your test suite to deterministically reproduce this failure pattern.
            </span>
          </div>
        </div>
      )}
    </div>
  );
};
