"""
Automated Pytest Regression Test Generator for Agent 365.

Converts diagnosed OpenTelemetry failure traces into standalone, executable
Pytest regression test scripts for CI/CD pipelines.
"""

from __future__ import annotations

import json
from typing import Any, Dict, List, Optional, Union

try:
    from models.trace import FullDiagnosisResponse
except ImportError:
    from backend.models.trace import FullDiagnosisResponse

from agent365.otel.models import OTelSpan
from agent365.otel.parser import build_digraph_from_otel_spans


def generate_pytest_regression_script(
    diagnosis: FullDiagnosisResponse,
    spans: List[Union[OTelSpan, Dict[str, Any]]],
) -> str:
    """
    Generate an executable Pytest script string from a diagnosed OTel trace.
    """
    parsed_spans: List[OTelSpan] = [
        s if isinstance(s, OTelSpan) else OTelSpan.from_otlp_dict(s)
        for s in spans
    ]

    trace_id = parsed_spans[0].trace_id if parsed_spans else "unknown_trace"
    root_cause_id = diagnosis.diagnosis.root_cause_node_id
    failure_category = diagnosis.diagnosis.failure_category

    # Find root cause span details
    root_span = next((s for s in parsed_spans if s.span_id == root_cause_id), None)
    root_name = root_span.name if root_span else "unknown_root_span"
    root_attrs = root_span.attributes if root_span else {}

    # Extract inputs and recorded tool outputs
    input_content = parsed_spans[0].attributes.get("input.value", "Agent query") if parsed_spans else ""
    recorded_tool_outputs = [
        {
            "span_id": s.span_id,
            "tool_name": s.attributes.get("tool.name", s.name),
            "output": s.attributes.get("output.value", s.attributes.get("note", "Tool output")),
            "status": s.status_code.value,
        }
        for s in parsed_spans
        if s.kind.value in ("TOOL", "RETRIEVER", "RAG")
    ]

    script = f'''"""
Automated Regression Test Generated by Agent 365.
Trace ID: {trace_id}
Failure Category: {failure_category}
Root Cause Span: {root_cause_id} ({root_name})
"""

import pytest

REGRESSION_TRACE_ID = "{trace_id}"
EXPECTED_FAILURE_CATEGORY = "{failure_category}"
EXPECTED_ROOT_CAUSE_SPAN_ID = "{root_cause_id}"

MINIMAL_INPUT = {json.dumps({"prompt": input_content}, indent=4)}
RECORDED_TOOL_OUTPUTS = {json.dumps(recorded_tool_outputs, indent=4)}
ROOT_CAUSE_ATTRIBUTES = {json.dumps(root_attrs, indent=4)}


def test_agent_regression_failure_isolation():
    """
    Verify that Agent 365 causal engine isolates the root cause correctly.
    """
    assert EXPECTED_FAILURE_CATEGORY in ["Retrieval", "Tool", "Coordination", "Unknown"]
    assert len(EXPECTED_ROOT_CAUSE_SPAN_ID) > 0
    assert isinstance(RECORDED_TOOL_OUTPUTS, list)


def test_root_cause_span_signature():
    """
    Ensure the root cause span maintains expected failure metadata.
    """
    assert ROOT_CAUSE_ATTRIBUTES is not None
'''
    return script
